// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;

public partial class Client
{
    public Guid IdClient { get; set; }
    public string ClientName { get; set; }
    public string Description { get; set; }
    public string FiscalAdress { get; set; }
    public string Vat { get; set; }
    public DateTime? Timestamp { get; set; }
    public string Status { get; set; }
    public Guid? FkUser { get; set; }
    public Guid? FkCountry { get; set; }
    public string Link { get; set; }
    public bool Suspended { get; set; }
    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();
    public virtual Country FkCountryNavigation { get; set; }
    public virtual User FkUserNavigation { get; set; }
    public virtual ICollection<PackagesClientsModule> PackagesClientsModules { get; set; } = new List<PackagesClientsModule>();
    public virtual ICollection<User> Users { get; set; } = new List<User>();
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}