// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using project_main.Models;
using System;
using System.Collections.Generic;

namespace project_main;

public partial class License
{
    public Guid IdLicenses { get; set; }
    public Guid FkIdPackage { get; set; }
    public Guid FkIdClient { get; set; }
    public int FkStatus { get; set; }
    public DateTime? StartDate { get; set; }
    public DateTime? FinishDate { get; set; }
    public Guid? FkIdUser { get; set; }
    public bool? PurchasedYear { get; set; }
    public int FkIdTransaction { get; set; }
    public virtual User FkUserNavigation { get; set; }
    public virtual Package Package { get; set; }
    public virtual LicenseStatus LicenseStatus { get; set; }
    public virtual Transaction Transaction { get; set; }
    public virtual ICollection<User> Users { get; set; }
}