// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using project_main.Models;
using System;
using System.Collections.Generic;

namespace project_main;

public partial class LicenseLog
{
    public int Id { get; set; }
    public int ActionType { get; set; }
    public Guid? FkUser { get; set; }
    public Guid FkClient { get; set; }
    public DateTime LogDatetime { get; set; }
    public string LogMessage { get; set; }
    public virtual User FkUserNavigation { get; set; }
    public virtual Client FkClientNavigation { get; set; }
    public virtual LicenseLogActionType FkActionTypeNavigation { get; set; }
}