// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;

public partial class LicenseStatus
{
    public int IdLicenseStatus { get; set; }
    public string Status { get; set; }
    public string Description { get; set; }
    public virtual ICollection<License> Licenses { get; set; }
}