// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;

public partial class Package
{
    public Guid IdPackage { get; set; }
    public string PackageName { get; set; }
    public string Description { get; set; }
    public DateTime? Timestamp { get; set; }
    public Guid? FkUser { get; set; }
    public decimal? PackageAnnualPrice { get; set; }
    public decimal? PackageMonthlyPrice { get; set; }
    public DateOnly? StartDate { get; set; }
    public DateOnly? FinishDate { get; set; }
    public Guid FkIdPackageParent { get; set; }
    public virtual User FkUserNavigation { get; set; }
    public virtual PackageParent FkPackageParentNavigation { get; set; }
    public virtual ICollection<PackagesClientsModule> PackagesClientsModules { get; set; } = new List<PackagesClientsModule>();
    public virtual ICollection<License> Licenses { get; set; }
}