// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;

public partial class PackagesClientsModule
{
    public Guid IdPackageClientModule { get; set; }
    public DateOnly? StartDate { get; set; }
    public DateOnly? FinishDate { get; set; }
    public string Notes { get; set; }
    public string PackageKey { get; set; }
    public DateTime? Timestamp { get; set; }
    public string Status { get; set; }
    public Guid? FkUser { get; set; }
    public Guid? FkPackage { get; set; }
    public Guid? FkModule { get; set; }
    public Guid? FkClient { get; set; }
    public virtual Client FkClientNavigation { get; set; }
    public virtual Module FkModuleNavigation { get; set; }
    public virtual Package FkPackageNavigation { get; set; }
    public virtual User FkUserNavigation { get; set; }
}