// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;

public partial class ProfilePicture
{
    public Guid IdProfilePicture { get; set; }
    public Guid FkIdUser { get; set; }
    public string FilePath { get; set; }
    public string FileName { get; set; }
    public string FileType { get; set; }
    public string Base64 { get; set; }
    public virtual User FkUserNavigation { get; set; }
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}