// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;

public partial class Role
{
    public Guid IdRole { get; set; }
    public string Role1 { get; set; }
    public string Notes { get; set; }
    public DateTime? Timestamp { get; set; }
    public string Status { get; set; }
    public Guid? FkUser { get; set; }
    public virtual User FkUserNavigation { get; set; }
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}