// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_main.Models;


public partial class UserPreference
{
    public Guid IdUser { get; set; }
    public bool NotificationBillingApp { get; set; }
    public bool NotificationBillingEmail { get; set; }
    public bool NotificationBillingSms { get; set; }
    public bool NotificationSystemApp { get; set; }
    public bool NotificationSystemEmail { get; set; }
    public bool NotificationSystemSms { get; set; }
    public bool NotificationSecurityApp { get; set; }
    public bool NotificationSecurityEmail { get; set; }
    public bool NotificationSecuritySms { get; set; }
    public bool NotificationMessageApp { get; set; }
    public bool NotificationMessageEmail { get; set; }
    public bool NotificationMessageSms { get; set; }
}